### ISSUE TITLE
Примеры кода из 8 части

### ISSUE THREAD

**Issue by niklv** [iliakan/webpack-screencast#1]
Нету файла маппинга сабмодулей.

**Comment by iliakan** [comment]
Каких сабмодулей? git?

**Comment by niklv** [comment]
Да, в git.

суббота, 28 ноября 2015 г. пользователь Ilya Kantor написал:

**Comment by iliakan** [comment]
Я их не использовал.

**Comment by niklv** [comment]
Хм. Просто в интерфейсе гитхаба у меня эти папки отображаются как сабмодули.
http://i.imgur.com/nnaeWMR.png
И при клонировании репозитория в папках ничего нет.

**Comment by iliakan** [comment]
может там .git есть внутри?

**Comment by iliakan** [comment]
это не подмодули, посмотрел - в раб. копии оказались .git там

**Comment by niklv** [comment]
У меня при клонировании репозитории в папках 08-live-reload-\* пусто.

**Comment by iliakan** [comment]
git pull ;)
